<header class="header">
    <div class="navpadding">
        <aside>
            <a href="index.php" class="logo"><img src="logo.png" alt="Segfault logo"></a>
        </aside>
        <nav class="navbar">
            <ul class="navmenu">
                <li><a href="index.php" class="navpage">Homepage</a></li>
                <li><a href="apply.php" class="navpage">Work with Us</a></li>
                <li><a href="about.php" class="navpage">About Us</a></li>
                <li><a href="jobs.php" class="navpage">Jobs</a></li>
                <li><a href="reach.php" class="navpage">Reach Out</a></li><!-- added lbyrnes-->
                <li><a href="manage.php" class="navpage">Manage EOIs</a></li>
                <li><a href="enhancements.php" class="navpage">Enhancements</a></li>
        </ul>
        </nav>
    </div>
</header>
